### ISSUE TITLE
Canalizar las discusiones mediante este repo

### ISSUE THREAD

**Issue by cecilios** [lenmus/roadmap#1]
LenMus es un proyecto abierto y esto implica, entre otras cosas, que es transparente, es decir, que todo el que esté interesado puede ver lo que está pasando, consultar documentos y código fuente, opinar y hacer sugerencias.

Por ello, si os parece bien, para canalizar las ideas y discusiones sobre la evolución y cambios a realizar en el programa LenMus os propongo utilizar las herramientas de trabajo en grupo usadas en LenMus. Para ello, utilizaríamos este repo.

**Comment by nanobarrera** [comment]
Perfecto.

**Comment by cecilios** [comment]
Veras que cuando hay algun comentario te llegan al correo

**Comment by nanobarrera** [comment]
Recibido, jajaja

**Comment by Sara-RG** [comment]
Uffff, me ha costado porque lo del inglés.... me puede, pero por fin, parece que estoy registrada y puedo escribir.
Perfecto

**Comment by Sara-RG** [comment]
No hay más participantes porque tengo que enviarles los mensajes para que puedan inscribirse. Dadme hasta mañana que hoy todavía es Domingo de Ramos.
Un abrazo,

**Comment by PedroGF83** [comment]
Hola compañerxs! perdón por la demora. Por acá ando yo también.
Quedo atento y leyendo!!
Un Abrazo

**Comment by cecilios** [comment]
Teneis que pinchar en el botón **Watch**, arriba del todo, a la derecha:

![watch](https://user-images.githubusercontent.com/5238679/78535008-b53e4b80-77eb-11ea-9d4a-874c55b4aaa7.png)

Porque si no, no estareis subscritos a este repo y no os enterareis de lo que pase, salvo que entreis ex profeso a mirar. Ahora os llega este mensaje porque habeis contestado algo en este hilo, pero para todo lo nuevo no os llegará nada.

Animo, pinchad en "Watch" que es gratis :smile:

**Comment by Sara-RG** [comment]
Le he dado a Watch y creo que ya lo tengo perfectamente configurado.
Hoy enviaré los correos al resto del grupo para que lo hagan.
Y la nueva versión del nivel I realizada por Marcelino, la subiré a Google después de echarle un vistazo.
Seguimos.
Un abrazo,

**Comment by cecilios** [comment]
Bien!!! Ya te veo metida. Me faltan Nano y Pedro. De todas maneras, espero a mañana por si se apunta el resto del grupo y os mando los primeros comentarios a los documentos de Drive, para empezar a organizar el trabajo y poder ver las cosas de una en una y con detalle.

**Comment by PedroGF83** [comment]
Ya estoy Cecilio? le di a "watch" y activé "be notified of all
conversations"
Es correcto?

*Pedro Garrido Fdez. "Niño de la Fragua"*

**Comment by PedroGF83** [comment]
Escribí desde el correo, so sorry. Ya ando por aquí again.

**Comment by nanobarrera** [comment]
Dentro

**Comment by Sara-RG** [comment]
Me parece perfecto. Debes dar ese tiempo porque ahora me dispongo a ponerlos al corriente.
A ver si mañana estamos todos metidos en GitHub.

**Comment by PacoPavon** [comment]
¡Buenos días!
Creo que estoy dentro.
Ánimo, cuidarse mucho y a trabajar en virtual.
Un abrazo

**Comment by cecilios** [comment]
@PacoPavon Sí, estas dentro. Bienvenido!!!

**Comment by DACILGM** [comment]
¡Hola, compañeros!

Ya he podido registrarme. Espero haberlo hecho bien. Un saludo!

**Comment by SergioMacias28** [comment]
¡Holaaaaaaa!

Creo que ya estoy dentro del hilo. ¡Un saludo!

**Comment by cecilios** [comment]
@SergioMacias28 y @DACILGM  Bienvenidos!!!
No os veo en la lista de "watchers" (seguidores del proyecto). Por favor, mirad esto que escribí https://github.com/lenmus/roadmap/issues/1#issuecomment-609635809

**Comment by DACILGM** [comment]
Creo que ya lo he hecho. Gracias!! Un saludo

**Comment by SergioMacias28** [comment]
Ya está solucionado, ¡Un saludo!

**Comment by cecilios** [comment]
Antes de comenzar a trabajar, unas indicaciones para que os vayais situando.

- Cualquiera puede abrir temas (issues). Sólo teneis que pinchar en el botón verde **New Issue**, arriba a la derecha.
![new-issue](https://user-images.githubusercontent.com/5238679/78662991-b2b62180-78d1-11ea-9c57-60f8b885267a.png)

- Cada tema debería ser lo más monográfico posible, para poder centrar la discusión. 
- Los temas son elementos vivos: si un tema empieza a contener mucha materia, se desdobla en varios. Esto lo suele hacer el moderador, yo en este caso, pero cualquiera de vosotros también puede hacerlo.
- Cuando un tema se da por resuelto, se cierra. Pero no desaparace. Siempre se puede consultar todo lo que se habló y por qué se adoptó una determinada decisión.
- Siempre podeis consultar los temas cerrados. Pinchad en la pestaña **Issues**:
![issues](https://user-images.githubusercontent.com/5238679/78663020-bd70b680-78d1-11ea-90e1-f1791d48e372.png)

y luego en el enlace **Closed**
![closed](https://user-images.githubusercontent.com/5238679/78663053-c792b500-78d1-11ea-8b15-d928488ef71e.png)

- Yo iré abriendo temas a medida que tenga cosas que plantear. Por favor haced vosotros lo mismo. Nos juntaremos con muchas cosas abiertas. Es normal.
- Siempre habrá muchos temas abiertos, pues se van abriendo a medida que surgen dudas, ideas nuevas o problemas. Eso no significa que se trabaje en todos los temas a la vez. Lo que se hace es priorizarlos y trabajar en los que se marquen como urgentes o mas prioritarios. Los restantes se pueden consultar para ir pensando, y se pueden contestar cosas, pero tendrán poca actividad porque el equipo estará concentrado en los temas marcados como prioritarios.

Aquí teneis un buen documento, corto y explicativo, para no informáticos, sobre GitHub y los *issues*, por si quereis información. Es un buen artículo pero ... está en Inglés. Sorry!
https://github.com/dwyl/github-reference

**Comment by cecilios** [comment]
Bueno, lo primero es agradeceros vuestra disposición a trabajar en esto y que os vayais a encargar de la dirección musical del proyecto. A ver si entre todos conseguimos hacer un gran proyecto!

**Comment by u09644676** [comment]
Hola. Soy Marcelino, no encontré foto mejor.
He subido un escrito en isues. No sé si es allío o quì donde debe estar...

**Comment by cecilios** [comment]
Bienvenido Marcelino !

**Comment by nanobarrera** [comment]
Hola, Marcelino!

**Comment by Sara-RG** [comment]
Bueno, parece que vamos estando todos. Me falta Elena. No cerremos este hilo hasta que estemos todos. Un abrazo,

**Comment by nanobarrera** [comment]
Genial.
