### ISSUE TITLE
Nombre y acceso a los "Ejercicios generales"

### ISSUE THREAD

**Issue by DACILGM** [lenmus/roadmap#11]
Buenas noches, compañeros:

Sara y yo hemos estado trabajando en una primera revisión del libro de ejercicios generales. Estas son nuestras primeras impresiones que podemos seguir desarrollando en nuestra reunión del martes. Así mismo hemos estado reflexionando sobre una posible secuenciación de contenidos de cada uno de los apartados del índice. En esta segunda sesión os las comentaremos.

- Título del libro: opinamos que se podría modificar para ajustarse mejor a la naturaleza de los ejercicios. Apuntamos las siguientes propuestas: 

- Entrenamiento auditivo
- Discriminación auditiva
- Ejercicios de audición
- Educación auditiva

- Eliminar el apartado Introducción: nos parece más operativo ir directamente al índice de contenidos.

- Consideramos que el bloque 2 (ejercicios para la educación del oído) y el bloque 3 (ejercicios de teoría) pueden reunirse en un mismo bloque.

Adjuntamos, a continuación, un primer índice de contenidos abierto a todo tipo de sugerencias:
ÍNDICE DE CONTENIDOS (entre paréntesis señalamos los puntos de los bloques 2 y 3 contenidos en cada uno de los apartados propuestos)

1. Identificación de notas (engloba 2.3 y 3.3)
2. Intervalos 
2.1. Identificación de intervalos (engloba 2.2 y 3.2)
2.2 Comparación de intervalos (engloba 2.1 y 3.3)
3. Escalas (engloba 2.5 y 3.5)
4. Tonalidades (engloba 2.6 y 3.1)
5. Acordes (engloba 2.4 y 3.4)
6. Cadencias (engloba 2.7 y 3.6)
7. Lectura a primera vista

**Comment by cecilios** [comment]
> Eliminar el apartado Introducción: nos parece más operativo ir directamente al índice de contenidos.

Me parece bien, especialmente teniendo en cuenta la idea que dijimos de no darle formato de libro y que sea un enlace  en otro sitio.

> Título del libro: opinamos que se podría modificar para ajustarse mejor a la naturaleza de los ejercicios

Estoy de acuerdo en que "Ejercicios Generales" es un mal título y que debería ser cambiado. Pero no veo claras las propuestas que haceis de:
> Entrenamiento auditivo
> Discriminación auditiva
> Ejercicios de audición
> Educación auditiva

pues transmiten la idea de que son sólo ejercicios de educación auditiva y eso no es correcto. Hay otros tantos ejercicios de 'otra cosa' que no se si es teoría, lectura a primera vista o qué.

Yo propondría algún título más neutro tal como "Compendio de ejercicios", especialmente si no le vamos a dar formato de libro y va a ser un enlace  en otro sitio.

**Comment by cecilios** [comment]
@u09644676 comenta en #13:

Lo encuentro todo razonable.

Suprimir Introducción y entrar directamente en los ejercicios: de acuerdo.
Sobre el Título: tomando en cuenta los títulos propuestos, yo lo vería así: Ejercicios de Educación Auditiva. (Es la "esencia de Libro, y es suficientemente completo. No que no sean "ejercicios" no debería ir ahí).

Sobre le Indice de Contenidos:
Lo veo bien como plan de trabajo. Seguramente cuando se trate de sistematizar los contendidos de cada apartado habrá que hacer algunas modificaciones. por ejemplo: en el 4. Tonalidades (engloba 2.6 y 3.4) posiblemente fuera mejor este "Tonalidades y armaduras"( se trata de distinguir tonalidades Mayor y menor; y de identificar armaduras en pentagrama. Son dos cosas distintas.)
En fin... es cuestión de ir aquilatando.

**Comment by cecilios** [comment]
> yo lo vería así: Ejercicios de Educación Auditiva. (Es la "esencia de Libro, 

Vuelvo a discrepar. No son sólo ejercicios de educación del oido, aunque eso sea el aspecto que más os ha gustado. Hay tantos ejercicios de educación auditiva como de teoría !

**Comment by DACILGM** [comment]
Hola, Cecilio:

Sí, lo que proponemos es unir la teoría y la audición. Por eso lo de englobar los dos bloques.

**Comment by cecilios** [comment]
@DACILGM  Sí, lo entiendo y no tengo objeción a unirlos en el mismo tema. Mi discrepancia es en hablar sólo de ejercicios de educación auditiva, pues ese título no responde al contenido. Aunque metamos en el mismo tema el ejercicio de teoria y el ejercicio de audición, eso no convierte todo en ejercicios de audición: siguen siendo dos ejercicios y uno sigue siendo de teoria.

**Comment by cecilios** [comment]
Poneos en la piel de un usuario que no conoce el programa y quiere hacer ejercicios de reconocer intervalos sobre una partitura. Si yo fuera ese usuario ¡jamás se me ocurriría pinchar en _"ejercicios de entrenamiento auditivo"_ para buscar el ejercicio de leer intervalos!

**Comment by cecilios** [comment]
O separarlos en dos enlaces distintos, a mi me da igual un solo libro de ejercicios que dos. Hacedlo como mejor veais que encaja en la pantalla de inicio y en vuestra idea pedagógica. Pero pensad que el usuario debe encontrar lo que quiere buscar sin tener que conocer el programa de antemano.

**Comment by Sara-RG** [comment]
Retomando, comienzo por el objetivo 1 y me parece bien llamar al enlace "Compendio de ejercicios".
Ciertamente, me gustaría buscar un título más original, para que se llamara la atención y motivara a entrar. En este sentido, propongo a vuestra consideración:
"Entrena con LenMus" o bien  "Entrenamiento progresivo" o  "Desarrolla tus habilidades musicales" (ya que los contenidos estarán secuenciados y distribuidos en tres niveles, tal como dijimos), pero repito que "Compendio de ejercicios" me parece bien (aunque muy clásico ¿quién quiere ponerse a hacer ejercicios?)

**Comment by cecilios** [comment]
Sí, lo de "Compendio de ejercicios" no suena bien :smile:
Tal como lo veo, lo que va a condicionar el título es dónde se coloca el enlace. Veo dos opciones extremas:
- Si el enlace es sólo una palabra en el menú entonces tendrá que ser algo corto, como "Ejercicios", "Entrenar" o "Hacer ejercicios".
- Si en vez de un enlace en el menú se coloca como un bloque en la pantalla de inicio, entonces pondría tener un título más atractivo, tal como los que propone Sara; además, tendría debajo un texto explicativo (ej. "ejercicios progresivos que te ayudarán a .......bla bla bla").
- Opciones intermedias no se me ocurren ¿Teniais pensado colocar este enlace en algún otro sitio?

**Comment by Sara-RG** [comment]
Creo que en un bloque en la pantalla de inicio podría ir bien, y además el texto explicativo debajo o cuando entraras en el bloque estaría fenomenal, pero no sé cómo tiene planteado esto Fernando en la pantalla de inicio ... ni qué piensan los demás.

**Comment by DACILGM** [comment]
A mí personalmente  me gusta "Entrena con Lenmus" (es muy motivador). Luego como bien dice Cecilio se podría añadir un texto que explicara mejor el propósito: "Desarrolla tus habilidades auditivas con una serie de ejercicios progresivos que te ayudarán a asimilar los distintos contenidos musicales"

**Comment by cecilios** [comment]
Sí, lo en "Entrena con LenMus" suena bien. Aunque sea Nano el principal responsable de la pantalla de inicio, quizá convendría que los demás también mirarais su diseño para ver cómo y cónde se encaja este enlace a los ejerecicios. Esta es la pantalla propuesta: https://github.com/lenmus/roadmap/issues/12#issuecomment-651270717

Hay un bloque pensado para que podais colgar vuestros videos, ya sean los del MOOC u otros que querais ir haciendo para enseñar a solfear, a leer, a entonar, etc. Si eso no se va a usar de momento, podría aprovecharse ese espacio para esto de los ejercicios.

**Comment by Sara-RG** [comment]
Cecilio, me parece bien utilizar ese espacio para los ejercicios, ya que de momento no tenemos vídeos preparados para colgar ahí.
Y estoy de acuerdo también con el texto explicativo que propone Dácil, aunque quizás (solo quizás) se pueda acortar un poco, generalizando de este modo: "Desarrolla tus habilidades musicales mediante ejercicios progresivos" Y no sé si convendría decir "Marca tu propio ritmo de aprendizaje".

**Comment by cecilios** [comment]
Entonces tomamos como opción preferida que el antiguo libro "Ejercicios Generales" sea ahora un contenido accesible desde la pantalla de inicio, algo así:
![bloque-ejercicios-generales](https://user-images.githubusercontent.com/5238679/97079376-a9816d80-15f3-11eb-9994-0b21dc1e0eb8.png)

Para el icono habría que buscar algo más apropiado. Y hay que consensuar el texto. He puesto una mezcla entre lo propuesto por Dacil y lo de Sara: "Desarrolla tus habilidades musicales con una serie de ejercicios progresivos que te ayudarán a asimilar los distintos contenidos. Marca tu propio ritmo de aprendizaje.".

**Comment by Sara-RG** [comment]
Me gusta mucho!!!!

**Comment by DACILGM** [comment]
¡A mi también!

**Comment by u09644676** [comment]
He visto las opciones presentadas en torno a este tema. Y la que se perfila como más adecuada (Entrena con LenMus con su leyenda explicativa, tal como presenta Cecilio me parecen válidas.  Y ciertamente debe aparecer en Pantalla Inicial, tal como se sugiere. Así que, por mi parte, ¡adelante!.

**Nota:** Aunque no tiene que ver con este 1º Objetivo, aprovecho para pedir que se considere la conveniencia de definir ya la denominación de los `Libros` que han de ir en Pantalla de Inicio.  Yo presenté una propuesta razonada el 22 de abril, que no ha tenido repuesta. Pienso que esto debe quedar fijado desde YA por ser parte integrante la Pantalla de Inicio que se está preparando.

**Comment by cecilios** [comment]
Bueno, como parece que hay acuerdo, podemos dar por cerrado este tema. Ahora hay que seguir definiendo cosas de la pantalla principal. Por favor, participad todos en eso (tema #12) porque lo que falta no son sólo aspectos de estética sino que hay que definir varias cosas, y la opinión y aportaciones de todos y cada uno de vosotros es importante. Por ejemplo, el tema que plantea Marcelino (#8) sobre el orden y denominación de los libros; o los restantes bloques a incluir en la pantalla principal.

@u09644676 Marcelino, te doy mi opinión en el tema #8 que es el sitio para discutirlo.
