### ISSUE TITLE
Libro de Ejercicios Generales. (Ideas)

### ISSUE THREAD

**Issue by u09644676** [lenmus/roadmap#13]
Lo encuentro todo razonable.

Suprimir  Introducción y entrar directamente en los ejercicios: de acuerdo.
Sobre el Título: tomando en cuenta los títulos propuestos, yo lo vería así:  Ejercicios de Educación Auditiva. (Es la "esencia de Libro, y es suficientemente completo. No que no sean "ejercicios" no debería ir ahí).

Sobre le Indice de Contenidos:
Lo veo bien como plan de trabajo. Seguramente cuando se trate de sistematizar los contendidos de cada apartado habrá que hacer algunas modificaciones. por ejemplo: en el 4. Tonalidades (engloba 2.6 y 3.4) posiblemente fuera mejor este "Tonalidades y armaduras"( se trata de distinguir tonalidades Mayor y menor; y de identificar armaduras en pentagrama. Son dos cosas distintas.)
En fin...  es cuestión de ir aquilatando.

**Comment by cecilios** [comment]
La idea de usar GitHub es para tener las discusiones agrupadas por temas. Cada _issue_ debe dedicarse a un sólo tema. Muevo tu respuesta al tema correspondiente #11 y cierro este.
