### ISSUE TITLE
Bloque "Primeros pasos con la aplicación"

### ISSUE THREAD

**Issue by cecilios** [lenmus/roadmap#22]
En la pantalla de inicio se ha incluido un bloque para sustituir el actual enlace a la "guia de estudio", que ahora se abriría al pulsar el botón "START":
![bloque-guia-estudio](https://user-images.githubusercontent.com/5238679/97103383-5b7c7080-16ac-11eb-9b60-1e1e1f224dd1.png)

Y más adelante podríamos pensar  (o lo podemos ir pensando desde ya) en sustituir ese documento por una especie de presentación, varias transparencias con alguna imagen y un texto pequeño, para destacar las principales ideas e introducir el programa. Algo así como lo que habreis visto en otros programas cuando hay una nueva versión. Porque eso de leer un documento largo se le hace muy árido a la gente.

**Comment by Sara-RG** [comment]
Totalmente de acuerdo. Me gusta.

**Comment by Sara-RG** [comment]
Cecilio, creo que esto ya lo habéis aclarado Nano y tú no?
¿Podría darse por zanjado?

**Comment by cecilios** [comment]
Sara yo creo que no hay nada decidido todavía. Sólo hay una propuesta de Nano a quien pedí que por favor copiara aquí su propuesta con el fin de poderla discutir y tomar la decisión en un sitio específico.

Esto de abrir un issue por tema, que os sigue pareciendo absurdo, es muy importante porque muchas veces a lo largo de la vida de un proyecto hay que reconsiderar decisiones o recordar por qué se tomo una decisión. Y si los argumentos están desperdigados por veinte temas mas otros tantos correos electrónico pues, comprenderéis que no hay forma de mantener una historia. Por otra parte facilita que cualquier participante que, por la razón que sea, haya estado ajeno a unos intercambios de opiniones, pueda rápidamente repasar un tema y ponerse al día, porque sabe que en ese issue es donde está todo.

Bueno, copio aquí la propuesta de Nano (https://github.com/lenmus/roadmap/issues/12#issuecomment-735448464):

> Descubre Lenmus 
>
> Lenmus es un programa totalmente gratuito para estudiar teoría de la música, practicar solfeo y mejorar tu oído musical. Si quieres saber cómo funciona, haz clic aquí. [Esto podría dirigir al Mooc, a la parte de Lenmus, con vídeos y textos]

Os dejo mis comentarios a esta propuesta, aunque como moderador, hubiera preferido ser el último en opinar. Pero dada la situación creo que no hay más remedio. Aquí va: El objetivo de este nuevo diseño de la pantalla de inicio era evitar que el usuario se sintiera perdido, dándole indicaciones claras sobré lo que se podía hacer y lo que iba a encontrar. En este sentido, se propuso un apartado con el título tentativo "Primeros pasos con la aplicación" orientado a dar instrucciones sobre **cómo usar el programa**. En consecuencia:

- El texto propuesto por Nano no cumple ese objetivo pues es un párrafo que describe qué es LenMus, no un párrafo para describir lo que puede encontrar si pulsa el enlace ¿Qué es "saber como funciona"? ¿Le vamos a explicar cómo está programado LenMus? ¿Le vamos a explicar otra cosa? ¿Para qué necesita el usuario pulsar ese enlace?. En fin, creo que sería mejor un texto en el sentido de que pulsando ese enlace se le van a mostrar videos explicativos, o que se le va llevar a una pantalla donde pase no-se-qué, o cualquier otra cosa más descriptiva. Yo puedo también hacer alguna propuesta al respecto pero esperaba primero vuestros comentarios y propuestas por dos razones: 1) como moderador creo que debo ser el último en opinar para no condicionar, y 2) vosotros como usuarios podeis hacer unas propuestas más acertadas que las mias como desarrollador.

- Nano propone un cambio en el título a "Descubre LenMus" sin argumentos. Dado que el propósito del apartado es explicar cómo utilizar el programa, creo que el título "Primeros pasos con la aplicación" es más descriptivo.

A parte de que hay que terminar de elaborar y decidir el título y el texto, queda por definir qué vamos a hacer cuando se pulse el enlace. Hay varias opciones, yo sugerí que podía hacerse una presentación, con slides; o de momento mostrar la actual guía de estudio. Nano ha propuesto "dirigir al Mooc, a la parte de Lenmus, con vídeos y textos". Me parece también una opción aceptable, pero tenemos que ver otras opiniones y llegar a alguna conclusión. En el caso de que sean los videos y textos del MOOC necesitamos materializar eso de alguna manera: ¿Saldrá una pantalla con la lista de videos y textos? ¿Ya existe? ¿Es un enlace permanente que siempre está accesible? 

En fin que, como puedes ver yo creo que esto está en mantillas y es preciso más participación y diálogo. Y no sólo de Nano, si no también de todos los demás. Si esto se reduce a lo que Nano y yo opinemos, creo que acabamos rápido a la hora de votar porque serán sólo dos votos y el mio (lo siento Nano) es de más peso :wink:

**Comment by Sara-RG** [comment]
Veamos, yo creo que vamos avanzando aunque es verdad que a los músicos parece que este sistema de tantos hilos nos está llevando "un poco a la locura". Disculpa, Cecilio, no te lo tomes a mal, son tantos los hilos abiertos... cuando llega un correo hay que buscar el hilo en el que se ha escrito, no aparece una señal en Git Hub que diga en cuál de ellos está la última información recibida, y es un esfuerzo constante por no perder justamente "el hilo"... pero no pasa nada. 
Retomo por tanto el tema de "Primeros pasos con la aplicación".  Vamos a hacerlo como tú dices, ya he hablado con Fernando, él contrastará contigo opiniones pero en realidad creo que vais en la misma línea solo que, efectivamente hay que ver concretamente a qué da acceso ese título, ¿a una guía del programa como había antes, a los vídeos sobre LenMus del MOOC (habría que retocarlos después de los cambios pero los que están hechos se podrían enlazar sin problema), a ambas cosas... ? Quizás eso no se pueda concretar ahora totalmente, pero sí poner ya un texto explicativo, orientado a la información que vaya ahí finalmente.
Y un poco de paciencia, que es que unos temas van conectados con otros, y esto parece un puzzle de 200000 piezas jajjjj

Y lo de "Descubre LenMus" supongo que ha sido un error, ya que ese es el título que le dimos finalmente al libro de Ejercicios Generales, y así lo he visto ya plasmado en la pantalla inicial propuesta.

Finalmente,, Cecilio, tú siempre tienes la última palabra (no en orden numérico necesariamente, sino por "peso específico" como creador del programa) con lo cual estamos siempre muy atentos a tus indicaciones y razonamientos (son siempre de gran interés).
Quiero ser optimista, vamos poco a poco adelante.

**Comment by cecilios** [comment]
Sara, dices que 
> cuando llega un correo hay que buscar el hilo en el que se ha escrito

Y efectivamente, tienes razón en que eso es pesado y lioso. Pero la buena noticia es que está todo pensado y resuelto por gente que lo sufrió antes. Si os fijais, el título del correo siempre acaba con el núero del hilo, en este caso el título que debería apareceros es **Re: [lenmus/roadmap] Bloque "Primeros pasos con la aplicación" (`#22`)**. El `#22` es el número del hilo, así que ya teneis una referencia rápida para encontrarlo.  Pero, todavía mejor, si os fijais, al final del correo siempre aparece una frase como esta:
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

Y eso de `view it on GitHub` es un enlace directo al hilo. Mi consejo es no leer el post en el correo sino buscar el enlace de abajo y pinchar para ir directamente a GitHub, leerlo allí y contestar.

Con respecto a los videos del MOOC, ¿están disponibles en YouTube o en algún otro sitio con el que enlazar?

**Comment by Sara-RG** [comment]
Sí, Cecilio, de acuerdo, si eso hacía jajjjj pero bueno, el entramado es sustancioso.

Los videos del MOOC están en el canal UCA de MOOC y se pueden enlazar, claro. Tendría que hablar con la persona que lo lleva y ver cómo hacerlo, pero es perfectamente viable. 
si estamos de acuerdo en eso, me pongo en marcha con ese tema.

**Comment by Sara-RG** [comment]
Hay que tener en cuenta que esos vídeos van referidos a la versión 5.3.1 y explican todo referido a esa versión, sin los cambios actuales.

**Comment by cecilios** [comment]
Sara, antes de mover nada yo creo que mejor pensemos bien lo que queremos hacer ¿Cual es exactamente vuestra idea?

Yo creo que seguramente no todos los videos del MOOC sean adecuados para mostrar aquí. Por ejemplo, pienso que los videos contando cómo instalar LenMus no tienen sentido pues si puede acceder a la pantalla de inicio es que ya ha conseguido instalar el programa.

Tambien teneis que valorar que el acceso 24h, 365 dias al año, desde cualquier parte del mundo y la carga para los servidores del MOOC. No creo que genere mucha carga porque serán muy pocos accesos, pero tienen que ser enlaces públicos permanentes. También tendeis que considerar la conveniencia de que los videos tengan al menos subtítulos en inglés.

Una idea que se me ocurre, para no cargar a la UCA y al MOOC con el tema de tener que mantener un servidor publico para los videos, es abrir un canal en YouTube con los videos del MOOC que sean de utilidad aquí. Eso permitiría además una línea futura de crecimiento, añadiendo, por ejemplo, videos prácticos con lecciones: primeros pasao para hacer los ejercicios de lectura, temas difíciles como el tresillo, etc. Y sin que para ello necesiteis depender de los recursos que os quiera dar la universidad.

En cualquier caso, no tengo claro como sería el enlace a esto del los videos del MOOC. Yo creo que habría que pasar por una ventana con la lista de videos y documentos, ordenados según la secuencia lógica en que deberían visionarse. ¿Proporciona el MOOC esa ventana? ¿Puede particularizarse para suprimir alguna cosa que no interese para LenMus? Quizá lo más sencillo sea que esa ventana sea del propio programa.

¿Cuales son vuestras ideas?
