### ISSUE TITLE
Aspecto de los libros

### ISSUE THREAD

**Issue by cecilios** [lenmus/roadmap#23]
Se habia comentado que el aspecto de los libros no gustaba porque parecían documentos word. Hubo un post de Cecilio (https://github.com/lenmus/roadmap/issues/12#issuecomment-650214304) donde se explicaba la situación y unas posibles alternativas, sencillas de realizar.

En https://github.com/lenmus/roadmap/issues/12#issuecomment-735448464 Nano comenta que

> Cecilio, la nueva propuesta que haces me parece acertada, con esa única página corrida, aunque se sacrifique la posibilidad de imprimir.

> Sí que insistiría en eliminar los hipervínculos azules, que siguen dando una imagen un poco anticuada, aunque por supuesto, muy intuitiva. Simplemente los sombrearía tal vez en gris o subrayarlo sin cambiar el color de texto o poner el texto en negrita y que cuando se pase con el ratón por encima, el cursor se transforme en una manita o algo parecido para indicar que se puede interactuar con esa parte del texto. Podría ser una de estas opciones: 

>clic aquí; clic aquí; clic aquí; clic aquí; o clic aquí.

Abro este issue, para mantener el tema más centrado y no mezclarlo con el diseño de la pantalla inicial, y doy mi opinión sobre el anterior comentario de Nano.

Tomo nota de tu voto: quitar la paginación y perder (por ahora) la posibilidad de imprimir los textos. 

Con respecto a los enlaces, aunque me gusta cuidar la estética, cuando hay conflicto doy prioridad a la funcionalidad sobre la estética pues siempre hay usuarios con algún tipo de problema visual que lo que necesitan es máxima claridad. Por ello, de las tres opciones planteadas:
- No apoyo la de texto en negrita, pues se confundirían con los textos en negrita que ya existen.
- La opción de sombrear el texto no sé si es posible. Puedo investigarlo y os digo.
- Subrayarlo sí es posible y no habría equivocos pues el subrayado no se ha usado en ningún texto; es simplemente cambiar el color del hipervínculo a negro.

**Comment by Sara-RG** [comment]
Respecto a la paginación, lo que queráis, como lo veáis mejor; no soy capaz de opinar sobre eso con mucha propiedad, pero me parece que realmente imprimir puede no ser muy importante. 
Y respecto a los enlaces, yo los vería mejor en algún color (no tiene que ser azul, aunque no importaría tampoco) y sin subrayar. Pero dicho esto, creo que debería resolverse como os parezca más adecuado y seguir adelante con otros temas.

**Comment by cecilios** [comment]
He revisado el programa y no es posible, por ahora, poner enlaces sombreados. Se puede cambiar el tipo de letra, poner en negrita o cursiva, cambiar el tamaño, cambiar el color y subrayar.

Una cosa **importante** a tener en cuenta es que los ejercicios generales también son un libro (aunque no vaya a aparecer com tal) y por ello, el aspecto de los enlaces en los ejercicios será el que elijamos para los libros.

**Comment by cecilios** [comment]
Con respecto a mi último comentario, aunque los ejercicios generales sean un libro, podría hacerse que el aspecto de los enlaces fuera distinto del de los restantes libros.

**Comment by Sara-RG** [comment]
Me parece bien esto último que dices, aunque no sé cómo los diferenciarías. Pero también pueden ir iguales ¿eh? no veo problema en ello. Para mí no es importante.
Personalmente, negrita me gusta para los textos activos, o un color, el que queráis, pero no subrayado, y puede ser igual en los libros y en Entrena con LenMus. 
Es solo una opinión, os dejo la decisión a vosotros, Cecilio y Fernando, que estáis más metidos en esto.

**Comment by cecilios** [comment]
Resumo el estado de opinión con respecto a los enlaces:

No es posible sombrearlos. De las restantes opciones:
- Nano (https://github.com/lenmus/roadmap/issues/23#issue-753446070): subrayarlo sin cambiar el color de texto o poner el texto en negrita
- Sara (https://github.com/lenmus/roadmap/issues/23#issuecomment-735935249): mejor en algún color (no tiene que ser azul, aunque no importaría tampoco) y sin subrayar.
- Cecilio (https://github.com/lenmus/roadmap/issues/23#issue-753446070): no en negrita, pues se confunden. Mejor subrayados y en algún color. Os dejo este enlace con los colores que, opino, deberíamos usar (https://www.w3.org/TR/2013/NOTE-WCAG20-TECHS-20130905/working-examples/G183/link-contrast.html ) Os comento seguidamenet mis razones.

### Mis argumentos ###
Un aspecto que diferencia al software desarrollado profesionalmente del realizado por aficionados es que se toman en consideración muchos aspectos que, a menudo, pasan inadvertidos. Por esta razón, las compañías de desarrollo de software (cualquiera, no solo las grandes que tenéis en mente) tienen muchas normas sobre las especificaciones que debe cumplir cualquier diseño.

Uno de estos conjuntos de normas internas son los que se refieren a usabilidad de los programas por personas con deficiencias visuales. Dado que Apple es el referente que usáis para los diseños, os dejo un párrafo de las guiás de diseño de Apple (https://developer.apple.com/design/human-interface-guidelines) en concreto, el que se refiere a los aspectos de los enlaces (https://developer.apple.com/design/human-interface-guidelines/accessibility/overview/user-interaction/):

> Consider giving links a visual indicator, such as an underline. It’s fine to use color to indicate a link, but if you use it as the only indicator, people with color blindness may not be able to perceive the distinction. For more information about using color to communicate in your app, see Color and Contrast.

Y el párrafo sobre colores que acaba de mencionar dice:

> Don’t rely solely on color to differentiate between objects or communicate important information. If your app uses color to convey information, be sure to provide text labels or glyph shapes so color blind users can understand it as well.

Como veis, para facilitar el uso del programa a personas con algún problema visual, se recomienda que los enlaces utilicen elementos gráficos quW3Ce permita diferenciarlos claramente.

El elemento diferenciado más utilizado es el subrayado. Aquí tenéis un artículo sobre buenas prácticas en el diseño de links (https://www.webfx.com/blog/web-design/designing-hyperlinks-tips-and-best-practices/), del que os extraigo estos dos párrafos:

> I think we can all still relate to seeing the standard blue, underlined hyperlink. It’s the default style of hyperlinks and they work well.

> Good hyperlinks should be distinctive from other types of text in a web page. According to several findings by usability researcher Dr. Nielsen, hyperlinks are most effective when they are a different color from other types of text in a web page and when they are underlined to denote that the text is clickable.


En resumen, el aspecto de los enlaces no es sólo una cuestión de estética y gustos personales, es sobre todo una cuestión de usabilidad. Por ello, considero que sólo deberíamos barajar opciones que sigan permitiendo distinguir los enlaces claramente, incluso a personas con problemas para ver los colores.

El W3C, organismo internacional que regula y controla los estándares para la web, recomienda que para satisfacer criterios de accesibilidad se utilicen enlaces subrayados y colores que tengan un contraste de al menos 3:1 con el negro. Y facilita una lista de colores que satisfacen ese criterio:
https://www.w3.org/TR/2013/NOTE-WCAG20-TECHS-20130905/working-examples/G183/link-contrast.html

**Comment by Sara-RG** [comment]
Ok.
Me parece que debemos tender por supuesto a la usabilidad más que a la estética, así que, totalmente de acuerdo, Cecilio. Las razones que das son de peso y las desconocía, muchas gracias por la información. 
Color, por tanto, azul, alguno de los que cumplan el criterio que dices: (0066CC, 6600FF, 3333FF, 3366CC) y subrayado.
Y puede ser igual en todos los libros, sin problema. 
Si nadie más opina, decidido.

**Comment by cecilios** [comment]
Sara, puesto que no ha habido más opiniones lo dejamos como dices.

En cuanto al aspecto de los libros, al no haber tampoco más opiniones, la votación ha quedao como sigue:
- Nano: quitar la paginación y perder la posibilidad de imprimir los textos.
- Sara: lo que queráis; imprimir puede no ser muy importante.
- Cecilio: la paginación me da igual. Pero si no paginamos perdemos la impresión y esto lo considero necesario.

No habiendo más votos, la conclusión es quitar la paginación. En cuanto a la impresión, la posibilidad de imprimir los libros fue una petición expresa de varios usuarios. Mi impresión es que mas que imprimir los textos, lo que quieren es imprimir algún ejercicio sobre el que tengan dudas, para consultarlo con el profesor. Como os dije, quitar la paginación obliga a programar una alternativa para dividir el texto en páginas y poderlo imprimir. 

Así que lo estudio y si no es mucho coste, quitamos la paginación y programo la impresión de otra forma. En caso de que la programación me vaya a llevar mucho tiempo, lo dejamos como está.


No habiendo más cuestiones abiertas con respecto al aspecto de los libros, se puede dar por cerrado este tema.

**Comment by Sara-RG** [comment]
Disculpa, ya sé que has cerrado el hilo y me parece bien lo que dices. Yo reo, Cecilio que si era petición de usuarios el poder imprimir, (y entiendo especialmente lo de los ejercicios) esto habría que mantenerlo, con lo cual, valora tal como has dicho el coste de quitar la paginación y programar de otra forma la impresión, y si te da excesivo trabajo, se deja como está y ya está.
Perfecto. Muchas gracias.
