### ISSUE TITLE
Plan de estudios

### ISSUE THREAD

**Issue by cecilios** [lenmus/roadmap#4]
Para guiar la ubicación, niveles y secuenciación de los actuales materiales y los futuros que hagamos quizá lo  primero que tendríamos que hacer sería tener muy claro el plan de estudios que va a seguir LenMus ¿qué opinais?
¿Teneis vosotros claro este tema?

Por si aporta algo, para los libros de lenguage musical, decidí utilizar la secuencia de temas de cuando yo estudié esa materia (años 2002-2006) y seguí el temario de los libros que estudié (Colección [Arco Iris](https://www.docenotas.com/8732/metodo-el-arco-iris/) para los cursos 1,2,3 y 4. El de 5ª fue otro libro. En aquel entonces el lenguage musical eran cinco años). Pero no pasé de escribir el libro 2 por falta de tiempo.

Y para la teoría y la educación del oido estuve mirando distintos planes de estudio y me encontré que cambiaban de una año a otro, y que incluso eran distintos entre conservatorios y Autonomias. Si a eso le unimos que LenMus quería tener una vocación internacional, me decanté por tratar de seguir un plan de estudios más estable que los Españoles y, a ser posible, de ambito internacional. Y tras mirar planes a nivel internacional me decanté por seguir los del [ABRSM](https://es.abrsm.org/media/62974/theory_syll_master_2018.pdf), pues son los más conocidos y ampliamente utilizados.

**Comment by Sara-RG** [comment]
La primera pregunta es si queremos que LenMus contenga por un lado libros de Lenguaje Musical y por otro Ejercicios de educación auditiva, con lo cual el programa tendría una vertiente teórica con temas que contendrían solo ejemplos auditivos a modo de explicación,  pero sin la posibilidad de realizar ejercicios, y los libros de educación auditiva, que solo contendrían ejercicios prácticos secuenciados por temas y estos organizados en niveles. 

Al entrar en LenMus el estudiante podría ir a los libros de Lenguaje Musical para reforzar  avanzar en los contenidos teóricos, o directamente a los ejercicios auditivos para realizar una  práctica. Estos ejercicios estarían organizados y secuenciados como decimos, y el estudiante iría avanzando según su interés y conocimientos.
Pero ¿queremos eso o buscamos otra estructura de LenMus?

**Comment by nanobarrera** [comment]
En relación a la versión ordenador o para la futura versión móvil?

**Comment by cecilios** [comment]
No hace falta seguir con esto
