### ISSUE TITLE
Necesidad de informáticos

### ISSUE THREAD

**Issue by cecilios** [lenmus/roadmap#5]
Pese a todas las ideas que tengamos y al esfuerzo que hagamos, el proyecto no podrá continuar si no conseguimos al menos un informático con bastante dedicación, aunque seria mejor varios con distintos grados de decdicación.

Tambien hay que volver a montar el equipo de traductores, especialmente si vamos a escribir más temas o a cambiar algunos de los existentes. La equipo que se habia ido formando les comuniqué, en 2012, que ya no iba a continuar el desarrollo de LenMus, pues estaba solo en esto y no podía hacer mas que mantener lo que habia. Y desde entonces no he vuelto a tener contacto con ellos. Tengo que volver a contactar y ver si alguno sigue interesado. Ahora mismo sólo tenemos al que hizo la traducción al Griego.

Tenemos que tratar de ir creando un equipo de informáticos y de colaboradores. Yo plantearía el objetivo de lograr a corto plazo algún informático, y a medio plazo (3-4 años) haber conseguido relanzar el proyecto y contar con un equipo detrás: informáticos, traductores, etc.

La tarea más urgente sería lanzar actuaciones de captación de informáticos y dar visibilidad al poyecto, que se vea que está activo de nuevo. Cosas como:

- Mostar al público que el proyecto se reactiva. Eso puede atraer a gente interesada en colaborar:
   - [ ] Informar en _issues_ de lenmus/lenmus de que estamos trabajando en los contenidos.
   - [ ] Volver a meter páginas de noticias en la web de LenMus.
   - [ ] Relanzar el blog.
  
- Tratar de captar programadores. Posibles ideas:
   - [ ] anuncio en web lenmus + página de help needed
   - [x] anuncio en SourceForge. Ver https://sourceforge.net/p/forge/helpwanted/programmers/thread/3a3f328605/
   - [x] anuncio en GitHub. Ver https://github.community/t5/Project-Development-Help-and/Looking-for-help-for-LenMus-project/m-p/53346#M5071
   - [ ] anuncio en foros
   - [ ] anuncios en vuestra Universidad
   - [ ] anuncios en foros de asociaciones de alumnos, en facultades de informática

   
- Se puede intentar lanzar un proyecto en plataformas de crowfounding (ej: kickstarter) para conseguir dinero. Y con dinero, contratar programadores.

En fin, son sólo algunas ideas. Si teneis más ideas ... por que yo ya no sé qué más hacer!! :disappointed_relieved:

**Comment by cecilios** [comment]
Me acaba de llegar la Newsletter de SourceForge y ...¡aparece destacada nuestra solicitud de ayuda !

Mirad hacie el final de la página:
https://mailchi.mp/newsletters/open-source-advocates-hope-they-dont-have-to-fork-qt

No quiere decir nada, pero por lo menos el anuncio y el proyecto tendrá muchísima más visibilidad. A ver si hay suerte y se apunta alguien.

**Comment by cecilios** [comment]
Buenas noticias, hoy me ha escrito un tal Robert Byerly, que quiere colaborar en el proyecto. Es profesor de universidad, ahora retirado, pero tiene alguna experiencia en desarrollo en el entorno Mac.

Hemos intercambiado un par de correos y está dispuesto a trabajar en esto. Quiere empezar con la creación del paquete para macOS.

Estoy ya en conversaciones con él, dándole instrucciones para empezar a trabajar.

**Comment by Sara-RG** [comment]
Olé!!!!! Magnífico, Cecilio.
Yo por mi parte sigo tramitando la reconversión de la partida económica para un informático  que sea capaz de realizar los instaladores de Mac. No he recibido respuesta aún.

**Comment by cecilios** [comment]
> los instaladores de Mac

Eso es lo que va a hacer Robert Byerly

**Comment by nanobarrera** [comment]
Maravilloso!

**Comment by PedroGF83** [comment]
Buenas noticias, sí!! yo he contactado con dos amigos informáticos y ninguno ha sabido encarar este encargo. Así que genial noticia ;)

**Comment by cecilios** [comment]
Este hilo aporta poco  y no hace falta.
