### ISSUE TITLE
Trabajos a corto plazo

### ISSUE THREAD

**Issue by cecilios** [lenmus/roadmap#6]
En https://github.com/lenmus/roadmap/issues/3#issuecomment-614469836 @marcelino propuso:

> En el CORTO PLAZO trabajar los dos campos en paralelo:
>  a) haciendo las correcciones y adaptaciones “técnicas” que requiera el programa y
>  b) revisando los “contenidos” para introducir leves modificaciones que se podrían limitar a esto:
>
>    - corregir erratas y algunos términos no exactos.
>   - cambiar la ubicación de algunos temas para hacer el proceso más ‘progresivos’.
>    - revisar los ejercicios para que guarden también esa ‘progresividad’.
>    - introducir (quizá) algunos nuevos temas que se echan en falta.

Abro este tema para hablar de estas actuaciones a corto plazo e ir concretando lo que haga falta.

**Comment by PedroGF83** [comment]
Buenas taddes,
Acabo de formar equipo con Sergio, alumno colaborador, y nos dedicamos a hacer chequeo a nivel de usuario con intención de ir registrando erratas y posibles mejoras.

**Comment by PedroGF83** [comment]
"Por términos no exactos" también entiendo lo de las traducciones que tengo por tarea. Pronto enviaré un listado con las modificaciones que haré en los textos en español para que de deis el visto bueno antes de hacer ningún cambio.

**Comment by PedroFragua** [comment]
Compañerxs,
Acabo de realizar 41 correcciones/sugerencias en el libro 1. Consisten en traducciones puntuales y ligeros cambios de aire en algunos párrafos, siempre guiándome de lo que me sugirió Marcelino. Las propuestas deben ser supervisadas y aceptadas para que se realicen los cambios.

**Comment by PedroFragua** [comment]
La última actualización de la tabla de registro de incidencias del chequeo a nivel de usuario y a nivel musical, ha sido compartida hace unas horas.
Quedamos atentxs para saber de su utilidad ;)
