### ISSUE TITLE
Identificar intervalos (3.2)

### ISSUE THREAD

**Issue by cecilios** [lenmus/roadmap#7]
Os veo poco participativos. No se si es que estais muy ocupados o qué pasa, pero hace falta que participeis. Hay que aportar ideas e ir opinando, de forma que podamos, entre todos, ir definiendo las cosas y poder tomar decisiones. Quizá hemos estado hablando de temas muy abstractos. Os propongo un tema más concreto a ver si os animais un poco.

Parece claro que hay que establecer niveles para los ejercicios. Os propongo comenzar a analizar los niveles para algún ejercicio concreto, para ver qué nos encontramos. He elegido uno que me ha parecido sencillo para empezar, el ejercicio _“**3.2 Identificar intervalos**”_.

Es un ejercicio de teoría, no de educación del oido. Para empezar con algo para pensar, me acabo de inventar seis grados de dificultad y los he distribuido para los tres primeros niveles:

Nivel I
- 1: Intervalos (solo como un número).
- 2: Intervalos perfectos, mayores y menores (no se permiten alteraciones)

Nivel II
- 3: Intervalos perfectos, mayores y menores (hasta una alteración)
- 4: También aumentados / disminuidos (hasta una alteración)
- 5: También doble aumentados / disminuidos (hasta dos alteraciones)

Nivel III
- 6: Intervalos compuestos (hasta dos octavas)

Pero viendo los parámetros de configuración del ejercicio, veo que además de los intervalos en cada grados de dificultad, hay que pensar tambíen los restantes parámetros:

- Tipo de intervalo: ¿siempre melódico?
- Armaduras y claves: ¿Cuáles se usaran en cada grados de dificultad? Supongo que deberían ir en consonancia con las que se estudian en el libro de lectura de ese curso.
- Número de líneas adicionales por encima/debajo: idem

Esto de decidir cuantos niveles, que se mete en cada nivel, cuantas etapas en cada nivel y qué parámetros de configuración no se hacerlo. Os expongo aqui la primera “ocurrencia”. Espero que vosotros sí sepais hacerlo. Venga, a pensar y a enviar ideas para ver si avanzamos en algo.

**Comment by u09644676** [comment]
Hola, Cecilio: 
Efectivamente la participación no parece "desbordante"...
Quizá por falta de concretar acciones puntuales. Con esto de los intervalos tú ya tenemos un tema  abierto para debatir. Yo ya tengo elaborado todo un plan de trabajo sobre intervalos. Es lo que sería el  TEMA 5º  de esa  futura ¿hipotética? nueva estructuración en tres niveles.
Como es muy largo para traerlo aquí, apunto algunas ideas directrices sobre el estudio de intervalos.
- Los ejercicios deberían ir junto con la exposición teórica, imbricados con ella (no en otra ubicación del programa).
- NO multiplicar los niveles. Bastan tres. 
- Hay que partir de lo más elemental. Olvidarse de presentar al alumno cosas que todavía no ha estudiado. Por tanto olvidarse en un primer nivel de armaduras, alteraciones, etc.
NO hay que preocuparse de las alteraciones, porque los intervalos son siempre los mismos, tengan los alteraciones que tengan...
- El orden de estudio sería:
NIVEL I: Definirlos. Nomenclatura. Aprender a identificarlos visualmente. Ejercitarse en la identificación auditiva, de momento solo intervalos **ascendentes,** y en este orden: 
+ Intervalos de 4ª y de 5ª. Intervalos.
+ intervalos de 2ª y de 7ª. 
+ Intervalos de 3ª y de 6ª.

NIVEL II. (que todavía no está hecho) Los mismos intervalos, pero "descendentes". Intervalos mayores y menores / aumentados y disminuidos.

NIVEL III. Se abordarían los intervalos "armónicos" (no antes).

No me quiero extender más. Espero que en video - conferencia se termines de precisar objetivos y plan de trabajo.
Marcelino.




-

**Comment by SergioMacias28** [comment]
Hola
Estoy de acuerdo en que los intervalos melódicos son los que deben encontrarse en el nivel 1, y proponer los armónicos para un nivel más avanzado, puesto que puede ser difícil para alguien sin ninguna relación con la teoría musical encontrarse en el nivel 1 con un intervalo armónico, al menos en mi caso como amateur me sería más complicado. 
La separación en niveles para la proposición de los intervalos que propone Marcelino me parece bastante razonable.

**Comment by cecilios** [comment]
@SergioMacias28
A mi me parece sensato dejar los armónicos para niveles mas avanzados, pero tenemos que decidir dónde los metemos.

El trabajo que hay que hacer, para cada ejercicio, es:
- ver qué parámetros de configuración tiene
- cómo asignamos valores coherentes a esos parámetros para ir haciendo niveles de dificultad progresivos.
- como distribuimos luego esos niveles de dificultad progresivos en cursos (lo que habeis llamado Niveles I, II y II)

El enfoque inverso, si os resulta más cómodo, sería, para cada ejercicio:
- Establecer los cursos en los que ese ejercicio debe practicarse
- Establecer los niveles del ejercicio dentro del curso
- Definir los parámetros de configuración para cada uno de esos niveles.
- Visto el resultado, seguramente habrá configuraciones de parámetros no aplicadas. Decidir qué hacer con esas configuraciones. Posiblemente lleve a tener que reconsiderar la distribución en cursos y niveles realizada.

Por cierto, yo prefería hablar de "Cursos I, II, III" en vez de Niveles y dejar el término 'nivel' para la gradación dentro de un curso, porque me quedo sin términos JaJaJa!

**Comment by cecilios** [comment]
@u09644676 Puff! tocas muchas cosas. Voy haciendo mis comentarios de uno en uno.
 
> Los ejercicios deberían ir junto con la exposición teórica, imbricados con ella (no en otra ubicación del programa).

Estoy de acuerdo. Esa era la idea original del programa: un lector de libros interactivos. Pero luego vino la realidad:
- Antes de poder hacer un libro había que programar los ejercicios.
- Como no había nadie para escribir los textos transcurría un monton de tiempo hasta que el ejercicio podía meterse en el libro, correctamente configurado para cada lección. De echo, a dia de hoy hay muchos ejercicios que no tiene todavia el texto donde meterlos.

Solución: un libro desde el que todos los ejercicios estuvieran accesibles.
Ventajas:
- Los ejercicios están disponibles desde el momento en que se programan, sin esperar a los textos.
- El alumno puede localizar rápidamente el ejercicio que quiere practicar sin tener que ir de libro en libro buscando.

Inconvenientes:
- Los ejercicios, en este libro general, no están configurados, dejando a que cada alumno configure cada ejercicio de acuerdo a lo que quiera practicar en cada momento.

La solución sería la que me habeis transmitido y he tratado de reflejar en #2: configuraciones predefinidas por niveles y una opcion de configuración libre.

Para estudiantes avanzados siempre hará falta la opción de poder configurar un ejercicio como desee, ya que facilita poder estudiar esas cosas en las que más fallas. Por ejemplo, si yo tengo dificultad en distinguir de oido una sexta aumentada de una septima, me gustaria poder configurar el ejercicio de intervalos para que sólo genere esos dos intervalos en vez de tener que estar escuchando todos los intervalos y solo, de vez en cuando, que me aparezca una sexta o una septima.

Yo soy partidario de:
- Los ejercicios van junto con la exposición teórica, imbricados con ella.
- Por pragmatismo y facilidad para el alumno, mantendría un sitio donde poder ir directamente a los ejercicios. Pero en ese sitio tendrían que estar organizados (y configurados) por niveles. Y ademas una opción para personalizarlos.

**Comment by cecilios** [comment]
@u09644676 
 
> NO multiplicar los niveles. Bastan tres.

Entiendo que te refieres al material actualmente existente. Yo lo tenía en dos niveles asi que no lo veo raro.

Pero tenemos que dejar la puera abierta a seguir incluyendo nuevos materiales para cursos más avanzados. Ahora hagamos tres cursos, pero cuando tomemos decisiones tengamos siempre en mente que el programa debe poder seguir mejorando y continuar con más cursos, sin que eso nos obligue a reestructurar lo que ya tenemos.

**Comment by cecilios** [comment]
@u09644676 Tu distribuición en niveles:

> de momento solo intervalos ascendentes, y en este orden:
>       Intervalos de 4ª y de 5ª. 
>       Intervalos de 2ª y de 7ª.
>       Intervalos de 3ª y de 6ª.

No olvidemos que en este hilo estamos tratando de definir los cursos y niveles para el ejercicio de teoria: reconocer los intervalos en un pentagrama.

Entiendo que estas de acuerdo en que dentro de un NIVEL (curso) hay niveles para los ejercicios:

CURSO I
    Nivel 1. Intervalos de 4ª y de 5ª.
    Nivel 2. Intervalos de 2ª y de 7ª. (mas los de 4ª y 5ª o sin ellos)
    Nivel 3. Intervalos de 3ª y de 6ª (mas los anteriores o sin ellos)
    ¿Haria falta un Nivel 4, para practicar todos?.

- sería identificarlos sólo por número no por tipo (mayores y menores / aumentados y disminuidos)
- No hay alteraciones accidentales ni armaduras

**Comment by cecilios** [comment]
Acabo de subir este documento
https://github.com/lenmus/roadmap/blob/master/docs/Teoria.Identificar-intervalos.md

para ir recogiendo lo que vamos definiendo para este ejercicio.

**Comment by cecilios** [comment]
Se cierra de momento. Si en el futuro fuera bnecesario, se reabre o se crea otro issue.
